# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  setup-bazel:
    description: |
      Setup the Bazel build system used for building Android projects
    parameters:
      bazel-version:
        type: string
        default: "bazel"
    steps:
      - run:
          name: Add Bazel Apt repository
          command: |
            sudo apt install curl gnupg
            curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
            sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
            echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
      - run:
          name: Install Bazel from Apt
          command: | 
            sudo apt update && sudo apt install << parameters.bazel-version >>

jobs:
  build:
    parameters:
      bazel-version:
        description: "Pinned Bazel version Replace with your one"
        default: "bazel-3.2.0"
        type: string
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - setup-bazel:
          bazel-version: <<parameters.bazel-version>>
      - run:
          name: Run Docker build and push
          command: |
            sudo ln -s /usr/bin/<< parameters.bazel-version >>  /usr/bin/bazel
            ./scripts/docker-login.sh
            make push



workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - jizu